var json_CircuitoHistricoeArqueolgicodaPeqfricabrLein8105de20deSetde2018_6 = {
"type": "FeatureCollection",
"name": "CircuitoHistricoeArqueolgicodaPeqfricabrLein8105de20deSetde2018_6",
"features": [
{ "type": "Feature", "properties": { "Name": "Venerável Confraria Nossa Senhora da Lampadosa", "NATUREZA": null, "TIPO": null, "ENDERE__O": null, "DESCRICAO": null, "CLNP": null, "ANO_DO_TOM": null, "ESFERA_DE_ (Esfera de legislação)": null, "LEG_ESTADU": null, "LEG_FEDERA": null, "LEG_MUNICI": null }, "geometry": { "type": "Point", "coordinates": [ -43.1826542, -22.9060365 ] } },
{ "type": "Feature", "properties": { "Name": "Igreja de São Gonçalo Garcia e São Jorge", "NATUREZA": null, "TIPO": null, "ENDERE__O": null, "DESCRICAO": null, "CLNP": null, "ANO_DO_TOM": null, "ESFERA_DE_ (Esfera de legislação)": null, "LEG_ESTADU": null, "LEG_FEDERA": null, "LEG_MUNICI": null }, "geometry": { "type": "Point", "coordinates": [ -43.1875048, -22.9050101 ] } },
{ "type": "Feature", "properties": { "Name": "Igreja de Santo Elesbão e Santa Efigênia", "NATUREZA": "Bem Cultural de Natureza Material", "TIPO": "Templo Religioso", "ENDERE__O": "Rua da Alfândega, 219", "DESCRICAO": "Inaugurada em 1754, a Igreja de Santo Elesbão e Santa Efigênia mantém seu aspecto original praticamente inalterado. Construída para abrigar uma confraria formada por negros, é uma tópica representante da arquitetura religiosa do século XVIII no Ri", "CLNP": "06005300219", "ANO_DO_TOM": "2001", "ESFERA_DE_ (Esfera de legislação)": "Estadual", "LEG_ESTADU": "Processo nº E-18/001.043/1999 - Provisório: 14/8/2001", "LEG_FEDERA": null, "LEG_MUNICI": null }, "geometry": { "type": "Point", "coordinates": [ -43.183764170448086, -22.903675065570312 ] } },
{ "type": "Feature", "properties": { "Name": "Igreja de Nossa Senhora do Rosário e São Benedito e todo o seu acervo", "NATUREZA": "Bem Cultural de Natureza Material", "TIPO": "Templo Religioso", "ENDERE__O": "Rua Uruguaiana, 77", "DESCRICAO": "Teve origem com a fusão de duas irmandades, a Irmandade do Rosário e a de São Benedito dos Homens Pretos. A construção da igreja teve início em 1700. Seu interior hoje é bem simples, devido a um incêndio em 1967, que destruiu a ornamentação ori", "CLNP": "06298400077", "ANO_DO_TOM": "1938", "ESFERA_DE_ (Esfera de legislação)": "Federal", "LEG_ESTADU": null, "LEG_FEDERA": "Livro Histórico vol. 1, insc. 10livro Belas Artes, vol.1, inscrição 24 de 7/4/1938", "LEG_MUNICI": null }, "geometry": { "type": "Point", "coordinates": [ -43.18028, -22.904068 ] } },
{ "type": "Feature", "properties": { "Name": "Igreja de Nossa Senhora da Candelária e todo o seu acervo", "NATUREZA": "Bem Cultural de Natureza Material", "TIPO": "Templo Religioso", "ENDERE__O": "Praça Pio X, s/n", "DESCRICAO": "De características neoclássicas, a Igreja da Candelária foi construída a partir de 1775 pela Irmandade do Santíssimo Sacramento e possui bela fachada em cantaria, portas trabalhadas em bronze e interior revestido em \n\nmármore. A pintura do interior", "CLNP": "08890600000", "ANO_DO_TOM": "1938", "ESFERA_DE_ (Esfera de legislação)": "Federal", "LEG_ESTADU": null, "LEG_FEDERA": "Livro Histórico vol. 1, insc. 12livro Belas Artes, vol. 1, inscrição 26 de 14/4/1938", "LEG_MUNICI": null }, "geometry": { "type": "Point", "coordinates": [ -43.178133858326916, -22.900996441327905 ] } },
{ "type": "Feature", "properties": { "Name": "Casa França-Brasil (antiga Alfândega)", "NATUREZA": "Bem Cultural de Natureza Material", "TIPO": "Edificação", "ENDERE__O": "Rua Visconde de Itaboraí, 20", "DESCRICAO": "Um dos raros remanescentes da arquitetura de Grandjean de Montigny, a construção data de 1820 e foi concebida para abrigar a primeira Praça do Comércio do Rio de Janeiro. Com espaço interno versátil, a construção teve vários usos como Alfândega", "CLNP": "06306500020", "ANO_DO_TOM": "1983", "ESFERA_DE_ (Esfera de legislação)": "Federal", "LEG_ESTADU": null, "LEG_FEDERA": "Livro Histórico vol. 1, insc. 36livro Belas Artes, vol.1, inscrição 75 de 24/5/1938", "LEG_MUNICI": null }, "geometry": { "type": "Point", "coordinates": [ -43.175923, -22.900586 ] } },
{ "type": "Feature", "properties": { "Name": "Igreja de Santa Rita de Cássia (incluindo o largo de Santa Rita em frente à igreja)", "NATUREZA": "Bem Cultural de Natureza Material", "TIPO": "Templo Religioso", "ENDERE__O": "Largo de Santa Rita, s/n", "DESCRICAO": "Foi construída entre 1720 e 1751, quando se tornou sede da paróquia. Era um dos templos onde condenados rezavam antes de ser conduzidos à forca. Tem frontão barroco e torre sineira.", "CLNP": "06249700000", "ANO_DO_TOM": "1938", "ESFERA_DE_ (Esfera de legislação)": "Federal", "LEG_ESTADU": null, "LEG_FEDERA": "Livro Histórico vol. 1, insc. 79, livro Belas Artes, vol.1, inscrição 165 de 15/7/1938", "LEG_MUNICI": null }, "geometry": { "type": "Point", "coordinates": [ -43.180711, -22.900331 ] } },
{ "type": "Feature", "properties": { "Name": "Sítio Arqueológico do Cais do Valongo", "NATUREZA": "Bem Cultural de Natureza Material", "TIPO": "Elemento Urbano", "ENDERE__O": "Praça Jornal do Comércio", "DESCRICAO": null, "CLNP": "19197300000", "ANO_DO_TOM": "2018", "ESFERA_DE_ (Esfera de legislação)": "Estadual", "LEG_ESTADU": "Processo nº E-18/001/100.095/2018 - Provisório :3/12/2018", "LEG_FEDERA": null, "LEG_MUNICI": null }, "geometry": { "type": "Point", "coordinates": [ -43.187235979538919, -22.896815967085505 ] } },
{ "type": "Feature", "properties": { "Name": "Docas D. Pedro II", "NATUREZA": "Bem Cultural de Natureza Material", "TIPO": "Edificação", "ENDERE__O": "Avenida Barão de Tefé, 75", "DESCRICAO": null, "CLNP": "06321400075", "ANO_DO_TOM": "2017", "ESFERA_DE_ (Esfera de legislação)": "Federal", "LEG_ESTADU": null, "LEG_FEDERA": "Livro do Tombo Histórico, Volume III, fls. 137, insc. 719", "LEG_MUNICI": null }, "geometry": { "type": "Point", "coordinates": [ -43.186709, -22.896566 ] } },
{ "type": "Feature", "properties": { "Name": "Cemitério dos Pretos Novos", "NATUREZA": null, "TIPO": null, "ENDERE__O": null, "DESCRICAO": null, "CLNP": null, "ANO_DO_TOM": null, "ESFERA_DE_ (Esfera de legislação)": null, "LEG_ESTADU": null, "LEG_FEDERA": null, "LEG_MUNICI": null }, "geometry": { "type": "Point", "coordinates": [ -43.192913697058124, -22.896101245146667 ] } },
{ "type": "Feature", "properties": { "Name": "Conjunto arquitetônico e urbanístico do Morro do Valongo", "NATUREZA": "Bem Cultural de Natureza Material", "TIPO": "Conjunto Urbano", "ENDERE__O": "Rua Camerino, s/n", "DESCRICAO": "Teve origem no século XVIII, provavelmente ligado às atividades comerciais das redondezas, que tinham como principal mercadoria o escravo africano. O jardim foi projetado pelo paisagista Luiz Rey na gestão do Prefeito Pereira Passos.", "CLNP": "06040000000", "ANO_DO_TOM": "1938", "ESFERA_DE_ (Esfera de legislação)": "Federal", "LEG_ESTADU": null, "LEG_FEDERA": "Livro Belas Artes vol.1, insc. 157 livro Histórico, vol. 1, inscrição 65 de 30/6/1938", "LEG_MUNICI": null }, "geometry": { "type": "Point", "coordinates": [ -43.187470034084377, -22.898272306479434 ] } },
{ "type": "Feature", "properties": { "Name": "Centro Cultural Municipal José Bonifácio", "NATUREZA": "Bem Cultural de Natureza Material", "TIPO": "Edificação", "ENDERE__O": "Rua Pedro Ernesto, 80", "DESCRICAO": "Prédio em estilo neoclássico, projetado por Francisco Joaquim Bethencourt da Silva e concluído em 1877 para abrigar a Escola Municipal José Bonifácio. Os recursos que viabilizaram o empreendimento foram resultado de doações destinadas originalment", "CLNP": "06351100080", "ANO_DO_TOM": "1983", "ESFERA_DE_ (Esfera de legislação)": "Municipal", "LEG_ESTADU": null, "LEG_FEDERA": null, "LEG_MUNICI": "Decreto n° 4.321 de 14/11/1983" }, "geometry": { "type": "Point", "coordinates": [ -43.194289298248584, -22.8960902987181 ] } },
{ "type": "Feature", "properties": { "Name": "Praça da Harmonia", "NATUREZA": null, "TIPO": null, "ENDERE__O": null, "DESCRICAO": null, "CLNP": null, "ANO_DO_TOM": null, "ESFERA_DE_ (Esfera de legislação)": null, "LEG_ESTADU": null, "LEG_FEDERA": null, "LEG_MUNICI": null }, "geometry": { "type": "Point", "coordinates": [ -43.191629, -22.8955145 ] } },
{ "type": "Feature", "properties": { "Name": "Pedra do Sal", "NATUREZA": "Bem Cultural de Natureza Material", "TIPO": "Elemento Urbano", "ENDERE__O": "Rua Argemiro Bulcão, s/n", "DESCRICAO": "Anteriormente denominada como Quebra-Bunda e Pedra da Prainha, a Pedra do Sal ficou assim conhecida por ficar nas redondezas de onde se carregava o sal. Neste local se instalaram os primeiros negros da Saúde, bem como as Tias Baianas. Ali nasceram as ro", "CLNP": "06376800000", "ANO_DO_TOM": "1984", "ESFERA_DE_ (Esfera de legislação)": "Estadual", "LEG_ESTADU": "Processo nº E-18/300.048/84 - Provisório: 23/11/1984 Definitivo: 11/5/1987", "LEG_FEDERA": null, "LEG_MUNICI": null }, "geometry": { "type": "Point", "coordinates": [ -43.185557697058186, -22.897947542765699 ] } },
{ "type": "Feature", "properties": { "Name": "Largo de São Francisco da Prainha", "NATUREZA": null, "TIPO": null, "ENDERE__O": null, "DESCRICAO": null, "CLNP": null, "ANO_DO_TOM": null, "ESFERA_DE_ (Esfera de legislação)": null, "LEG_ESTADU": null, "LEG_FEDERA": null, "LEG_MUNICI": null }, "geometry": { "type": "Point", "coordinates": [ -43.1841321, -22.8976435 ] } },
{ "type": "Feature", "properties": { "Name": "Morro da Conceição", "NATUREZA": null, "TIPO": null, "ENDERE__O": null, "DESCRICAO": null, "CLNP": null, "ANO_DO_TOM": null, "ESFERA_DE_ (Esfera de legislação)": null, "LEG_ESTADU": null, "LEG_FEDERA": null, "LEG_MUNICI": null }, "geometry": { "type": "Point", "coordinates": [ -43.1834788, -22.8990642 ] } },
{ "type": "Feature", "properties": { "Name": "Praça dos Estivadores/ Largo do depósito", "NATUREZA": null, "TIPO": null, "ENDERE__O": null, "DESCRICAO": null, "CLNP": null, "ANO_DO_TOM": null, "ESFERA_DE_ (Esfera de legislação)": null, "LEG_ESTADU": null, "LEG_FEDERA": null, "LEG_MUNICI": null }, "geometry": { "type": "Point", "coordinates": [ -43.187750631581977, -22.899257465384732 ] } },
{ "type": "Feature", "properties": { "Name": "Remanescente da casa de nascimento de Machado de Assis", "NATUREZA": null, "TIPO": null, "ENDERE__O": null, "DESCRICAO": null, "CLNP": null, "ANO_DO_TOM": null, "ESFERA_DE_ (Esfera de legislação)": null, "LEG_ESTADU": null, "LEG_FEDERA": null, "LEG_MUNICI": null }, "geometry": { "type": "Point", "coordinates": [ -43.1895088, -22.897934 ] } },
{ "type": "Feature", "properties": { "Name": "Associação Cultural e Recreativa Afoxé Filhos de Gandhi", "NATUREZA": null, "TIPO": null, "ENDERE__O": null, "DESCRICAO": null, "CLNP": null, "ANO_DO_TOM": null, "ESFERA_DE_ (Esfera de legislação)": null, "LEG_ESTADU": null, "LEG_FEDERA": null, "LEG_MUNICI": null }, "geometry": { "type": "Point", "coordinates": [ -43.1873556, -22.8997247 ] } },
{ "type": "Feature", "properties": { "Name": "Companhia Nacional de Navegação Costeira", "NATUREZA": null, "TIPO": null, "ENDERE__O": null, "DESCRICAO": null, "CLNP": null, "ANO_DO_TOM": null, "ESFERA_DE_ (Esfera de legislação)": null, "LEG_ESTADU": null, "LEG_FEDERA": null, "LEG_MUNICI": null }, "geometry": { "type": "Point", "coordinates": [ -43.1895495, -22.8929507 ] } }
]
}
