var json_Espaosdesociabilidadeecultura_20 = {
"type": "FeatureCollection",
"name": "Espaosdesociabilidadeecultura_20",
"features": [
{ "type": "Feature", "properties": { "imagem": "<img src='images/OL43.jpg' width='300' alt=''>", "Nome": "Quilombo Cultural Casa do Nando ", "Temporalidade": "Séc. XXI", "Ano": 2013.0, "Endereço": "Rua Camerino, 176", "Descrição": "Conhecido como \"Quilombo Cultural Casa do Nando\" ou \"Quilombo Cultural Urbano\", a Casa do Nando é um espaço dedicado a atividades culturais, debates, música e culinária afro-carioca.", "Parte da iniciativa Viva Pequena África": null, "Fonte": null, "Link": "https://www.instagram.com/acasadonando/" }, "geometry": { "type": "Point", "coordinates": [ -43.18517, -22.90184 ] } },
{ "type": "Feature", "properties": { "imagem": "<img src='images/OL44.jpg' width='300' alt=''>", "Nome": "Casa Savana", "Temporalidade": "Séc. XXI", "Ano": 2024.0, "Endereço": "Rua Camerino,162", "Descrição": "Casa de cultura e eventos com foco na música e gastronomia afro-brasileira.", "Parte da iniciativa Viva Pequena África": null, "Fonte": null, "Link": "https://casasavana.com.br/agenda" }, "geometry": { "type": "Point", "coordinates": [ -43.18545, -22.90152 ] } },
{ "type": "Feature", "properties": { "imagem": "<img src='images/OL45.jpg' width='300' alt=''>", "Nome": "Casa Omolokum ", "Temporalidade": "Séc. XXI", "Ano": 2018.0, "Endereço": "Rua Tia Ciata 51", "Descrição": "Local dedicado à cultura e gastronomia afro-brasileira.", "Parte da iniciativa Viva Pequena África": null, "Fonte": null, "Link": "https://www.instagram.com/casaomolokum/" }, "geometry": { "type": "Point", "coordinates": [ -43.18593, -22.89784 ] } },
{ "type": "Feature", "properties": { "imagem": "<img src='images/OL46.jpg' width='300' alt=''>", "Nome": "Centro Cultural Capiberibe 27", "Temporalidade": "Séc. XXI", "Ano": 2020.0, "Endereço": "Rua Capiberibe 27", "Descrição": "O Centro Cultural Capiberibe 27 é um sonho compartilhado por artistas e empreendedores, de diversas formações profissionais, que compraram mais do que um prédio histórico abandonado em ruínas: levaram junto a ideia de resgatar a memória deste local, tão importante para a cultura do país. No século XX, a edificação abrigou a antiga Fundição Zani, de onde saíram obras que se espalharam pelo Brasil e por diversos países. Foram feitos na antiga fundição monumentos como a escultura da cabeça do Zumbi, na Avenida Presidente Vargas, e o “Glória Imortal aos Fundadores de São Paulo”, no Páteo do Colégio, em São Paulo.", "Parte da iniciativa Viva Pequena África": null, "Fonte": "-https://www.instagram.com/p/Ch5KaXtJgGN/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==", "Link": "https://capiberibe27.com/" }, "geometry": { "type": "Point", "coordinates": [ -43.20407, -22.90219 ] } },
{ "type": "Feature", "properties": { "imagem": "<img src='images/OL47.jpg' width='300' alt=''>", "Nome": "Mocamba Livre", "Temporalidade": "Séc. XXI", "Ano": 2019.0, "Endereço": "Rua do Livramento, 98", "Descrição": "O Mocamba Livre é um espaço afro-originário, no coração da Pequena África, na rua do Livramento com a esquina do pecado. Um Quilombo Urbano Cultural focado nas gingas das encruzas e nas alquimias das pajelanças. Um quarteirão que não recebeu a maquiagem da revitalização do projeto porto maravilha.", "Parte da iniciativa Viva Pequena África": null, "Fonte": null, "Link": "https://www.instagram.com/mocambalivre/" }, "geometry": { "type": "Point", "coordinates": [ -43.19239, -22.89716 ] } },
{ "type": "Feature", "properties": { "imagem": "<img src='images/OL48.jpg' width='300' alt=''>", "Nome": "Casa de Cultura - Volta ao mundo e conexões", "Temporalidade": "Séc. XXI", "Ano": 2024.0, "Endereço": "Rua do Rosário, 24", "Descrição": "Espaço de lazer e cultura afro-brasileira.", "Parte da iniciativa Viva Pequena África": null, "Fonte": null, "Link": "https://www.instagram.com/casadeculturavmc/" }, "geometry": { "type": "Point", "coordinates": [ -43.1753, -22.90149 ] } },
{ "type": "Feature", "properties": { "imagem": "<img src='images/OL49.jpg' width='300' alt=''>", "Nome": "Mirante do Valongo", "Temporalidade": "Séc. XXI", "Ano": 2021.0, "Endereço": "Ladeira Pedro Antônio, 53", "Descrição": "Espaço de lazer, música e gastronomia.", "Parte da iniciativa Viva Pequena África": null, "Fonte": null, "Link": "https://www.instagram.com/mirantedovalongo/" }, "geometry": { "type": "Point", "coordinates": [ -43.18705, -22.89891 ] } }
]
}
