var json_Espaosdesociabilidadeecultura_15 = {
"type": "FeatureCollection",
"name": "Espaosdesociabilidadeecultura_15",
"features": [
{ "type": "Feature", "properties": { "Imagem": "<img src='images/OL40.JPG' width='300' alt=''>", "Nome": "Quilombo Cultural Casa do Nando ", "Temporalidade": "Séc. XXI", "Ano": 2013.0, "Endereço": "Rua Camerino, 176", "Descrição": "Conhecido como \"Quilombo Cultural Casa do Nando\" ou \"Quilombo Cultural Urbano\", a Casa do Nando é um espaço dedicado a atividades culturais, debates, música e culinária afro-carioca.", "Fonte": null, "Link": "https://www.instagram.com/acasadonando/" }, "geometry": { "type": "Point", "coordinates": [ -43.18517904412068, -22.901904545723603 ] } },
{ "type": "Feature", "properties": { "Imagem": "<img src='images/OL41.JPG' width='300' alt=''>", "Nome": "Casa Savana", "Temporalidade": "Séc. XXI", "Ano": 2024.0, "Endereço": "Rua Camerino,162", "Descrição": "Casa de cultura e eventos com foco na música e gastronomia afrobrasileira. ", "Fonte": null, "Link": "https://casasavana.com.br/agenda" }, "geometry": { "type": "Point", "coordinates": [ -43.18545, -22.90152 ] } },
{ "type": "Feature", "properties": { "Imagem": "<img src='images/OL42.JPG' width='300' alt=''>", "Nome": "Casa Omolokum ", "Temporalidade": "Séc. XXI", "Ano": 2018.0, "Endereço": "Rua Tia Ciata 51", "Descrição": "Local dedicado a cultura e gastronomia afrobrasileira. ", "Fonte": null, "Link": "https://www.instagram.com/casaomolokum/" }, "geometry": { "type": "Point", "coordinates": [ -43.18593, -22.89784 ] } },
{ "type": "Feature", "properties": { "Imagem": "<img src='images/OL43.JPG' width='300' alt=''>", "Nome": "Centro Cultural Capiberibe 27", "Temporalidade": "Séc. XXI", "Ano": 2020.0, "Endereço": "Rua Capiberibe 27", "Descrição": "O Centro Cultural Capiberibe 27, de quase 1500 m2, é um sonho compartilhado por artistas e empreendedores, de diversas formações profissionais, que compraram mais do que um prédio histórico abandonado em ruínas: levaram junto a ideia de resgatar a memória deste local, tão importante para a cultura do país. A antiga fundição Zani, de onde saíram obras que se espalham pelo Brasil e por diversos países, funcionou neste mesmo endereço, Rua Capiberibe 27, no século passado. Foram feitos aqui monumentos como a escultura da cabeça do Zumbi, na Avenida Presidente Vargas, e o “Glória Imortal aos Fundadores de São Paulo”, no Páteo do Colégio, em SP, entre outros.", "Fonte": "-https://www.instagram.com/p/Ch5KaXtJgGN/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==", "Link": "https://capiberibe27.com/" }, "geometry": { "type": "Point", "coordinates": [ -43.20407, -22.90219 ] } },
{ "type": "Feature", "properties": { "Imagem": "<img src='images/OL44.JPG' width='300' alt=''>", "Nome": "Mocamba Livre", "Temporalidade": "Séc. XXI", "Ano": 2019.0, "Endereço": "Rua do Livramento, 98", "Descrição": "MOCAMBA LIVRE é um espaço Afro-Originário, no coração da pequena África, na rua do Livramento com a esquina do pecado. Um QUILOMBO URBANO CULTURAL focado nas gingas das encruzas e nas alquimias das pajelanças. Um quarteirão que não recebeu a maquiagem da revitalização do projeto porto maravilha.", "Fonte": null, "Link": "https://www.instagram.com/mocambalivre/" }, "geometry": { "type": "Point", "coordinates": [ -43.19239, -22.89716 ] } },
{ "type": "Feature", "properties": { "Imagem": "<img src='images/OL45.JPG' width='300' alt=''>", "Nome": "Casa de Cultura - Volta ao mundo e conexões", "Temporalidade": "Séc. XXI", "Ano": 2024.0, "Endereço": "Rua do Rosário, 24", "Descrição": "Espaço de lazer e cultura afrobrasileira", "Fonte": null, "Link": "https://www.instagram.com/casadeculturavmc/" }, "geometry": { "type": "Point", "coordinates": [ -43.1753, -22.90149 ] } },
{ "type": "Feature", "properties": { "Imagem": "<img src='images/OL46.JPG' width='300' alt=''>", "Nome": "Mirante do Valongo", "Temporalidade": "Séc. XXI", "Ano": 2021.0, "Endereço": "Ladeira Pedro Antônio, 53", "Descrição": "Espaço de lazer, música e gastronomia. ", "Fonte": null, "Link": "https://www.instagram.com/mirantedovalongo/" }, "geometry": { "type": "Point", "coordinates": [ -43.18705, -22.89891 ] } }
]
}
