var json_RodasdeCapoeiraeofciobrdosmestresdeCapoeira_18 = {
"type": "FeatureCollection",
"name": "RodasdeCapoeiraeofciobrdosmestresdeCapoeira_18",
"features": [
{ "type": "Feature", "properties": { "Imagem": "<img src='images/PI50.jpg' width='300' alt=''>", "Manifestação": "Roda de Capoeira da Casa de Cultura VME", "Endereço": "Rua do Rosário, 24", "Descrição": "Aula gratuita de capoeira todo domingo às 9 da manhã na Casa de Cultura Volta do Mundo. Mestre Ephrain e Formando Escadão. ", "Ano": "2024", "Instância do Tombamento": "Federal, Estadual e Municipal", "Ano do Tombamento": "2008, 2009 e 2022", "Nº do Processo": "Livro das formas de expressão, Lei estadual 5577/2009 e Lei municipal 7.364/2022", "Fonte": null, "Links": "https://www.instagram.com/casadeculturavmc/" }, "geometry": { "type": "Point", "coordinates": [ -43.17541, -22.90143 ] } },
{ "type": "Feature", "properties": { "Imagem": "<img src='images/PI51.jpg' width='300' alt=''>", "Manifestação": "Tribos Capoeira Rio de Janeiro", "Endereço": "Av. Rio Branco, 120 ", "Descrição": "Associação de apoio à Cultura, Arte Vida Capoeira. Treinos de Capoeira com turmas exclusivas para jovens, adultos, iniciantes, intermediários e graduados. Professor Careca, Tribos Capoeira RJ. Supervisão: Mestrando Tyson DF, Mestre Canhoto Pá.", "Ano": "Não foi identificado o ano de início. ", "Instância do Tombamento": "Federal, Estadual e Municipal", "Ano do Tombamento": "2008, 2009 e 2022", "Nº do Processo": "Livro das formas de expressão, Lei estadual 5577/2009 e Lei municipal 7.364/2023", "Fonte": null, "Links": "https://www.instagram.com/triboscapoeirarj" }, "geometry": { "type": "Point", "coordinates": [ -43.17832, -22.90472 ] } },
{ "type": "Feature", "properties": { "Imagem": "<img src='images/PI52.jpg' width='300' alt=''>", "Manifestação": "Grupo de Capoeira GCASA", "Endereço": "R. Camerino, 176", "Descrição": "Grupo GCASA organizado e liderado por Mestre Neco Pelourinho.\nTreinos segundas e quartas às 18:30 na @acasadonando", "Ano": "1994", "Instância do Tombamento": "Federal, Estadual e Municipal", "Ano do Tombamento": "2008, 2009 e 2022", "Nº do Processo": "Livro das formas de expressão, Lei estadual 5577/2009 e Lei municipal 7.364/2024", "Fonte": null, "Links": "https://www.instagram.com/gcasa.mestreneco/" }, "geometry": { "type": "Point", "coordinates": [ -43.18516, -22.90182 ] } },
{ "type": "Feature", "properties": { "Imagem": "<img src='images/PI53.jpg' width='300' alt=''>", "Manifestação": "UCRB - Associação Cultural e Desportiva de Capoeira Universo Raízes do Brasil", "Endereço": "Praça Jornal do Comércio", "Descrição": "Roda do Mestre Antônio Kapueira que acontece toda Terça e Sexta às 18h no Cais do Valongo (em frente ao Hospital dos Servidores", "Ano": "Não foi identificado o ano de início. ", "Instância do Tombamento": "Federal, Estadual e Municipal", "Ano do Tombamento": "2008, 2009 e 2022", "Nº do Processo": "Livro das formas de expressão, Lei estadual 5577/2009 e Lei municipal 7.364/2025", "Fonte": null, "Links": "https://www.instagram.com/ucrb_pequena_africa/" }, "geometry": { "type": "Point", "coordinates": [ -43.18767, -22.89732 ] } },
{ "type": "Feature", "properties": { "Imagem": "<img src='images/PI54.jpg' width='300' alt=''>", "Manifestação": "UCRB - Associação Cultural e Desportiva de Capoeira Universo Raízes do Brasil", "Endereço": "Rua Sacadura Cabral, 109", "Descrição": "Roda do Mestre Antônio Kapueira que acontede todo Sábado às 14h30 no Dojo Pequena África - Centro de Cultura Única", "Ano": "Não foi identificado o ano de início. ", "Instância do Tombamento": "Federal, Estadual e Municipal", "Ano do Tombamento": "2008, 2009 e 2022", "Nº do Processo": "Livro das formas de expressão, Lei estadual 5577/2009 e Lei municipal 7.364/2026", "Fonte": null, "Links": "https://www.instagram.com/ucrb_pequena_africa/" }, "geometry": { "type": "Point", "coordinates": [ -43.18561, -22.89766 ] } },
{ "type": "Feature", "properties": { "Imagem": "<img src='images/PI55.jpg' width='300' alt=''>", "Manifestação": "Mestre Graúna do Porto", "Endereço": "Praça da Harmonia", "Descrição": "Célio Augusto Braga, o Mestre Graúna do Porto, é morador da região portuária desde os 10 anos de idade. Mestre Graúna é fundador do bloco Alegria Portuária e trabalha há mais de 30 anos como mestre e instrutor de capoeira na região, tendo dado aula em escolas, no Centro Cultural José Bonifácio e na Praça da Harmonia. ", "Ano": null, "Instância do Tombamento": "Federal, Estadual e Municipal", "Ano do Tombamento": "2008, 2009 e 2022", "Nº do Processo": "Livro das formas de expressão, Lei estadual 5577/2009 e Lei municipal 7.364/2027", "Fonte": "CATARINO, Gabriel. PERSONAGENS DA REGIÃO: Mestre Graúna. Olhar dos Vizinhos no Jornal da Zona, n. 3, Out. 2020. Disponível em: <https://museudeartedorio.org.br/wp-content/uploads/2020/12/O-Olhar-dos-Vizinhos-no-Jornal-da-Zona_3a-edi%C3%A7%C3%A3o-2.pdf>. Acesso em: 20 ago. 2025.", "Links": "https://www.instagram.com/mestre_grauna/" }, "geometry": { "type": "Point", "coordinates": [ -43.19172, -22.89555 ] } }
]
}
