var json_RodasculturaisdeHipHopbreasbatalhasderima_12 = {
"type": "FeatureCollection",
"name": "RodasculturaisdeHipHopbreasbatalhasderima_12",
"features": [
{ "type": "Feature", "properties": { "imagem": "<img src='images/PI56.jpg' width='300' alt=''>", "Manifestação": "Roda de Cultura da Central", "Endereço": "Rua Coronel Audomaro Costa, 113, Gamboa", "Descrição": "A roda acontece às quartas-feiras na Praça dos Cajueiros. ", "Parte da iniciativa Viva Pequena África": null, "Ano": "2019", "Instância do Tombamento": "Municipal e Estadual", "Ano do Tombamento": "2017, 2018 e 2022\n", "Nº do Processo": "Lei Municipal 6.301/2017. Lei Estadual nº 7837/2018. Lei Estadual nº 9.794/2022", "Fonte": "Mapas das Rodas de Rimas – Instituto Ensaio Rua. Disponível em: <https://ensaiorua.com.br/mapa-das-rodas-rimas/>. Acesso em: 28 ago. 2025.", "Links": "https://www.instagram.com/rodaculturalcentral/" }, "geometry": { "type": "Point", "coordinates": [ -43.19303, -22.90141 ] } },
{ "type": "Feature", "properties": { "imagem": "<img src='images/PI57.jpg' width='300' alt=''>", "Manifestação": "Roda de Cultura da Pedra do Sal", "Endereço": "Pedra do Sal", "Descrição": "Acontece toda 3ª quinta feira do mês na Pedra do Sal. ", "Parte da iniciativa Viva Pequena África": null, "Ano": "2019", "Instância do Tombamento": "Municipal e Estadual", "Ano do Tombamento": "2017, 2018 e 2022\n", "Nº do Processo": "Lei Municipal 6.301/2017. Lei Estadual nº 7837/2018. Lei Estadual nº 9.794/2022", "Fonte": "Mapas das Rodas de Rimas – Instituto Ensaio Rua. Disponível em: <https://ensaiorua.com.br/mapa-das-rodas-rimas/>. Acesso em: 28 ago. 2025.", "Links": "https://www.instagram.com/rodaculturaldapedradosal/" }, "geometry": { "type": "Point", "coordinates": [ -43.18525, -22.89807 ] } },
{ "type": "Feature", "properties": { "imagem": "<img src='images/PI58.jpg' width='300' alt=''>", "Manifestação": "Roda Cultural da Praça XV", "Endereço": "Praça XV de novembro", "Descrição": "A batatha da Praça XV acontece às quintas-feiras próxima a estação de VLT. ", "Parte da iniciativa Viva Pequena África": null, "Ano": "Não foi identificado o ano de início. ", "Instância do Tombamento": "Municipal e Estadual", "Ano do Tombamento": "2017, 2018 e 2022\n", "Nº do Processo": "Lei Municipal 6.301/2017. Lei Estadual nº 7837/2018. Lei Estadual nº 9.794/2022", "Fonte": null, "Links": "https://www.instagram.com/batalhadaxv/" }, "geometry": { "type": "Point", "coordinates": [ -43.17335, -22.90296 ] } },
{ "type": "Feature", "properties": { "imagem": "<img src='images/PI59.jpg' width='300' alt=''>", "Manifestação": "Batalha do Quinto Elemento", "Endereço": "Praça da Cruz Vermelha", "Descrição": "Batalha de conhecimento tradicional 45 seg realizada dentro de escolas públicas e privadas\n", "Parte da iniciativa Viva Pequena África": null, "Ano": "2016", "Instância do Tombamento": "Municipal e Estadual", "Ano do Tombamento": "2017, 2018 e 2022\n", "Nº do Processo": "Lei Municipal 6.301/2017. Lei Estadual nº 7837/2018. Lei Estadual nº 9.794/2022", "Fonte": null, "Links": "https://www.instagram.com/batalhaquintoelemento/" }, "geometry": { "type": "Point", "coordinates": [ -43.18828, -22.91191 ] } },
{ "type": "Feature", "properties": { "imagem": "<img src='images/PI60.jpg' width='300' alt=''>", "Manifestação": "Roda Cultural KGL", "Endereço": "Rua Joaquim Silva, 125", "Descrição": "A roda cultural da KGL (Catete, Glória, Lapa) acontece todo primeiro domingo do mês na Rua Joaquim Silva 125, Próximo aos Arcos da Lapa no  Rio de Janeiro.", "Parte da iniciativa Viva Pequena África": null, "Ano": "2015", "Instância do Tombamento": "Municipal e Estadual", "Ano do Tombamento": "2017, 2018 e 2022\n", "Nº do Processo": "Lei Municipal 6.301/2017. Lei Estadual nº 7837/2018. Lei Estadual nº 9.794/2022", "Fonte": "Mapas das Rodas de Rimas – Instituto Ensaio Rua. Disponível em: <https://ensaiorua.com.br/mapa-das-rodas-rimas/>. Acesso em: 28 ago. 2025.", "Links": "https://www.instagram.com/rodakgl/" }, "geometry": { "type": "Point", "coordinates": [ -43.179617729814474, -22.914220374839356 ] } },
{ "type": "Feature", "properties": { "imagem": "<img src='images/PI61.jpg' width='300' alt=''>", "Manifestação": "Batalha do Coliseu", "Endereço": "Praça Mário Lago", "Descrição": "A maior batalha do Rio de Janeiro se encontra no Buraco do Lume, próxima ao Largo da Carioca, em 2025 completam 6 anos de correria mantendo o movimento hip hop vivo e se consolidando como uma das maiores batalhas de Rima do país.", "Parte da iniciativa Viva Pequena África": null, "Ano": "2019", "Instância do Tombamento": "Municipal e Estadual", "Ano do Tombamento": "2017, 2018 e 2022\n", "Nº do Processo": "Lei Municipal 6.301/2017. Lei Estadual nº 7837/2018. Lei Estadual nº 9.794/2022", "Fonte": "Mapas das Rodas de Rimas – Instituto Ensaio Rua. Disponível em: <https://ensaiorua.com.br/mapa-das-rodas-rimas/>. Acesso em: 28 ago. 2025.", "Links": "https://www.instagram.com/bdcoliseu/" }, "geometry": { "type": "Point", "coordinates": [ -43.1762, -22.90611 ] } },
{ "type": "Feature", "properties": { "imagem": "<img src='images/PI62.jpg' width='300' alt=''>", "Manifestação": "Roda Cultural Catumbi", "Endereço": "Rua do Catumbi", "Descrição": "A roda cultural do Catumbi e? um movimento independente, que visa propagar a cultura underground. A roda acontecia na praça do Catumbi. No entanto, não temos informações sobre a continuidade do projeto.", "Parte da iniciativa Viva Pequena África": null, "Ano": "2019-2020", "Instância do Tombamento": "Municipal e Estadual", "Ano do Tombamento": "2017, 2018 e 2022\n", "Nº do Processo": "Lei Municipal 6.301/2017. Lei Estadual nº 7837/2018. Lei Estadual nº 9.794/2022", "Fonte": null, "Links": "https://www.instagram.com/rodaculturalcatumbi/" }, "geometry": { "type": "Point", "coordinates": [ -43.19502, -22.91757 ] } },
{ "type": "Feature", "properties": { "imagem": "<img src='images/PI63.jpg' width='300' alt=''>", "Manifestação": "Batalha do Ás", "Endereço": "Praça do Estácio", "Descrição": "A batalha do Ás nasceu em 2022 e acontece todos os sábados na Praça do Estácio a partir das 17h. ", "Parte da iniciativa Viva Pequena África": null, "Ano": "2022", "Instância do Tombamento": "Municipal e Estadual", "Ano do Tombamento": "2017, 2018 e 2022\n", "Nº do Processo": "Lei Municipal 6.301/2017. Lei Estadual nº 7837/2018. Lei Estadual nº 9.794/2022", "Fonte": "Mapas das Rodas de Rimas – Instituto Ensaio Rua. Disponível em: <https://ensaiorua.com.br/mapa-das-rodas-rimas/>. Acesso em: 28 ago. 2025.", "Links": "https://www.instagram.com/batalhadoas" }, "geometry": { "type": "Point", "coordinates": [ -43.20707, -22.91381 ] } }
]
}
